version: '2'

services:
  redis:
    image: redis:alpine

  postgres:
    image: docker.arvancloud.ir/postgres:latest
    environment:
      POSTGRES_USER: sentry
      POSTGRES_PASSWORD: sentry
      POSTGRES_DB: sentry
    volumes:
      - './postgres_db:/var/lib/postgresql/data'

  sentry:
    image: docker.arvancloud.ir/sentry:latest
    links:
     - redis
     - postgres
    ports:
     - 9000:9000
    environment:
      SENTRY_SECRET_KEY: 'Gmyuoz9LnBWrM3vXFGVD7WivfX3rJxfA83sc'
      SENTRY_POSTGRES_HOST: postgres
      SENTRY_DB_USER: sentry
      SENTRY_DB_PASSWORD: sentry
      SENTRY_REDIS_HOST: redis

  cron:
    image: docker.arvancloud.ir/sentry:latest
    links:
     - redis
     - postgres
    command: "sentry run cron"
    environment:
      SENTRY_SECRET_KEY: 'Gmyuoz9LnBWrM3vXFGVD7WivfX3rJxfA83sc'
      SENTRY_POSTGRES_HOST: postgres
      SENTRY_DB_USER: sentry
      SENTRY_DB_PASSWORD: sentry
      SENTRY_REDIS_HOST: redis

  worker:
    image: docker.arvancloud.ir/sentry:latest
    links:
     - redis
     - postgres
    command: "sentry run worker"
    environment:
      SENTRY_SECRET_KEY: 'Gmyuoz9LnBWrM3vXFGVD7WivfX3rJxfA83sc'
      SENTRY_POSTGRES_HOST: postgres
      SENTRY_DB_USER: sentry
      SENTRY_DB_PASSWORD: sentry
      SENTRY_REDIS_HOST: redis