{
 "title": "Monitoring RPS",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Request Status Code",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(ngx_http_requests_status_total[1m])) by (host, status)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Request Per Second",
   "type": "timeseries",
   "description": "Show Request per second",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(ngx_requests_total[1m])) by (host)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Methods",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(ngx_requests_method_total[1m])) by (host, method)",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Responses (latency)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(ngx_request_duration_seconds_bucket[1m])) by (le))",
     "legendFormat": "99%"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(ngx_request_duration_seconds_bucket[1m])) by (le))",
     "legendFormat": "0.90"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(ngx_request_duration_seconds_bucket[1m])) by (le))",
     "legendFormat": "0.50"
    }
   ]
  }
 ]
}